#!/usr/bin/env python

import sys,os

def build(bld):
    bld.add_subdirs('c_FFT6 c_Jacobi c_GraphSearch c_LUreduction c_Mandelbrot c_Pi c_FFT c_MolecularDynamic c_LoopsWithDependencies cpp_sortOpenMP c_QuickSort')
