#!/usr/bin/env python

import sys,os

def build(bld):

    for arch in bld.lst_variants:
        if arch == 'default' : continue

        obj = bld.new_task_gen('cc','program')
        obj.env  = bld.env_of_name(arch).copy()
        obj.source = """
            pt_test.c
        """
        obj.target = 'pt_test'
        if not arch.startswith('ecos'):
            obj.uselib_local = 'posixLayer_'+arch

        obj = bld.new_task_gen('cc','program')
        obj.env  = bld.env_of_name(arch).copy()
        obj.source = """
            pt_test2.c
        """
        obj.target = 'pt_test2'
        if not arch.startswith('ecos'):
            obj.uselib_local = 'posixLayer_'+arch

