#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, sys

def build(bld):
    obj = bld.new_task_gen('cxx', 'staticlib')
    obj.source = """
        RespClient.cpp
    """
    obj.target = 'RespClient'
    obj.export_incdirs = '.'
    obj.uselib = 'BOOST BOOST_SYSTEM ASIO BOOST_REGEX BOOST_FILESYSTEM'
