#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os, sys

def build(bld):
    obj = bld.new_task_gen('cxx', 'shlib')
    obj.source = """
        execLoader.cpp
    """
    obj.target = 'execLoader'
    obj.name = 'execLoader'
    obj.uselib = 'BOOST BFD'

    obj = bld.new_task_gen('pypp', 'shlib')
    obj.source = """
        execLoader.hpp
    """
    obj.target = 'execLoader_wrapper'
    obj.name = 'execLoader_wrapper'
    obj.uselib = 'BOOST BFD PYEXT BOOST_PYTHON'
    obj.uselib_local = 'execLoader'
    obj.start_decls = 'resp'
    obj.custom_code = """
execLoader = mb.class_('ExecLoader')
execLoader.variable('execImage').exclude()
execLoader.variable('programData').exclude()
execLoader.variable('progDim').exclude()
"""
