#!/usr/bin/env python

import sys, Options

def build(bld):
    obj = bld.new_task_gen('pypp','shlib')
    obj.source = """
        Callback.hpp
        Callback.cpp
    """
    obj.target='Callback';
    obj.start_decls = 'resp'
    obj.uselib='SYSTEMC_H TLM_H BOOST BOOST_PYTHON PYEMBED'
    obj.custom_code = """
"""
