#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    obj = bld.new_task_gen('pypp')
    obj.source ='''
        bitstreamSink.hpp
    '''
    obj.target='bS_wrapper';
    obj.uselib='BOOST BOOST_PYTHON TLM SYSTEMC_H'
    obj.uselib_local='systemc utils'
    obj.include = 'scwrapper tlmwrapper'
    obj.start_decls = 'bitstreamSink'
    obj.templates = ['bitstreamSink<unsigned int>']
    obj.custom_code = """
cls = mb.global_ns.classes(lambda decl : decl.name.startswith('bitstreamSink') )
for i in cls:
    i.include()
    i.alias = 'bitstreamSink32'
"""

