#!/usr/bin/env python

import sys,os
import Options


def build(bld):
    for arch in bld.lst_variants:
        if arch == 'default': continue

        obj = bld.new_task_gen('cc','staticlib')
        obj.env = bld.env_of_name(arch).copy()
        obj.find_sources_in_dirs('.')
        obj.includes     = obj.env['FFMPEG_SUBDIRS_INCLUDES']
        obj.name = 'avutil_'+arch
        obj.target = 'avutil'
        obj.env.append_unique('CPPFLAGS', bld.env_of_name(arch)['FFMPEG_SUBDIRS_ADDITIONALFLAGS'])

