#!/usr/bin/env python

# Build

def build(bld):
    obj = bld.new_task_gen('cxx', 'program')
    obj.source='''
        analyzer.cpp
        main.cpp
    '''
    obj.uselib = 'BOOST BOOST_PROGRAM_OPTIONS BOOST_FILESYSTEM BOOST_SYSTEM'
    obj.name         = 'memTraceViewer'
    obj.target       = 'memTraceViewer'
