#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):
    obj = bld.new_task_gen('cxx', 'cshlib')
    obj.source="""
        execLoader.cpp
    """
    obj.uselib_local = 'binutils BFDWrapper utils'
    obj.name = 'loader'
    obj.target = 'loader'

    obj = bld.new_task_gen('pypp')
    obj.source = """
        execLoader.hpp
    """
    obj.target = 'loader_wrapper'
    obj.uselib = 'BOOST BOOST_REGEX PYEXT BOOST_PYTHON'
    obj.uselib_local = 'loader'
    obj.start_decls = 'Loader'
    obj.custom_code = """
mb.global_ns.class_('Loader').member_function('getProgData').call_policies = call_policies.return_value_policy( call_policies.return_addressof )
"""
