#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    obj = bld.new_task_gen('pypp')
    obj.source ='''
        DummyBufferLT.hpp
    '''
    obj.target='DummyBufferLT32';
    obj.uselib = 'BOOST BOOST_PYTHON TLM SYSTEMC_H'
    obj.uselib_local = 'systemc utils'
    obj.include = 'scwrapper tlmwrapper'
    obj.start_decls = 'DummyBufferLT'
    obj.templates = ['DummyBufferLT<unsigned int>']
    obj.custom_code = """
cls = mb.global_ns.classes(lambda decl : decl.name.startswith('DummyBufferLT') )
cls.include()
for i in cls:
    i.alias = 'DummyBufferLT32'
"""

