#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-

def build(bld):

    obj = bld.new_task_gen('cxx', 'cshlib')
    obj.source = '''
        configEngine.cpp
        cEAllocationTable.cpp
    '''
    obj.target = 'configEngine'
    obj.uselib='SYSTEMC_H TLM BOOST TRAP'
    obj.uselib_local = 'systemc binutils utils'

    obj = bld.new_task_gen('pypp')
    obj.source ='''
        configEngine.hpp
    '''
    obj.target = 'cE_wrapper'
    obj.uselib = 'SYSTEMC_H TLM BOOST BOOST_PYTHON TRAP'
    obj.uselib_local = 'systemc configEngine'
    obj.include = 'scwrapper tlmwrapper trapwrapper'
    obj.start_decls = 'configEngine'
#    obj.templates = ['configEngine<unsigned int>']
    obj.custom_code = """
mb.global_ns.enumerations('deletionAlgorithm').include()
mb.global_ns.class_('configEngine').include()
"""
#cls = mb.global_ns.classes(lambda decl : decl.name.startswith('configEngine') )
#for i in cls:
#    i.include()
#    i.alias = 'configEngine32'

