#!/usr/bin/env python

# Build

def build(bld):
    obj = bld.new_task_gen('cxx', 'program')
    obj.source='''
        analyzer.c
    '''
    obj.includes     = '.'
    obj.name         = 'memAnalyzer'
    obj.target       = 'memAnalyzer'
