#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

# Build

import os, sys

def build(bld):
    obj = bld.new_task_gen('cxx', 'program')
    obj.source='''
        backtracer.cpp
    '''
    obj.includes = '../../src/profiler ../../src/bfdFrontend ../../lib/binutils-2.18/build/include'
    obj.uselib='BOOST OPCODES_CUSTOM BFD_CUSTOM LIBERTY_CUSTOM'
    obj.uselib += ' BOOST_REGEX BOOST_PROGRAM_OPTIONS'
    obj.name = 'backtracer'
    obj.target = 'backtracer'
    obj.env.append_unique('CXXFLAGS', '-O3')
    obj.uselib_local = 'BFDFrontend'
    if sys.platform != 'darwin':
        obj.env.append_unique('LINKFLAGS', '-Wl,-rpath-link -Wl,' + os.path.abspath('lib' + os.sep + 'binutils-2.18' + os.sep + 'build' + os.sep + 'lib'))
    obj.env.append_unique('LINKFLAGS', '-Wl,-rpath -Wl,' + os.path.abspath('lib' + os.sep + 'binutils-2.18' + os.sep + 'build' + os.sep + 'lib'))
