#ifndef PROTO_UTILS
#define PROTO_UTILS

enum privilegeType {INVALID = 0, SHARED, EXCLUSIVE};
#define REMOVE TLM_IGNORE_COMMAND
#define INVALIDATE TLM_READ_COMMAND
#define FLUSH TLM_WRITE_COMMAND

#endif // PROTO_UTILS
