#!/usr/bin/env python

def build(bld):

    for arch in bld.lst_variants:
        if arch == 'default': continue

        obj = bld.new_task_gen('cc','program')
        obj.env = bld.env_of_name(arch).copy()
        obj.source = """
            AStack.c
            c_testPath.c
            tg.c
        """
        obj.target = 'c_GraphSearch'
        obj.includes = '../../include'
        obj.uselib_local = 'ompsrc_cc_'+arch+'  gomp_'+arch+' pthread_stub_'+arch 
        obj.env.append_unique('CFLAGS', '-fopenmp')
        obj.env.append_unique('CCFLAGS', '-fopenmp')
        obj.env.append_unique('LINKFLAGS', '-lm')
